[package]
name = "uuid-lite2"
version = "1.10.1"
edition = "2024"
description = "A minimal random (v4) UUID generator."
license = "MIT"

[lib]
name = "uuid_lite2"
path = "src/lib.rs"

[dependencies]
getrandom = "0.4"

[features]
01v1m-o1UfnMVzc6MCHERBwg = []
02Uq_d5FMyc4D7vRZ49uHH-A = []
03wzQ2FCMtWyi4SKtrb6vmNw = []
04pf--k2ed4k349NUHyTbo1A = []
05wCEr8WE6_zkwbe7cEIwnpA = []
